----------> uses
# use Gaudi v* Gaudi (no_version_directory)
#   use GaudiSys *  (no_version_directory)
#     use Gaudi v22r4 Gaudi (no_version_directory)
#     use GaudiAlg v13r8 Gaudi (no_version_directory)
#       use GaudiKernel * Gaudi (no_version_directory)
#         use GaudiPolicy * Gaudi (no_version_directory)
#           use LCG_Settings *  (no_version_directory)
#           use Python * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.11)
#             use LCG_Configuration v*  (no_version_directory)
#               use LCG_Platforms *  (no_version_directory)
#             use LCG_Settings v*  (no_version_directory)
#           use tcmalloc * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.6.2)
#             use LCG_Configuration v*  (no_version_directory)
#             use LCG_Settings v*  (no_version_directory)
#             use libunwind v* LCG_Interfaces (no_version_directory) (native_version=5c2cade)
#               use LCG_Configuration v*  (no_version_directory)
#               use LCG_Settings v*  (no_version_directory)
#         use Reflex * LCG_Interfaces (no_version_directory)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#           use ROOT v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=5.34.36)
#             use LCG_Configuration v*  (no_version_directory)
#             use LCG_Settings v*  (no_version_directory)
#             use GCCXML v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=0.9.0_20150423)
#               use LCG_Configuration v*  (no_version_directory)
#               use LCG_Settings v*  (no_version_directory)
#             use Python v* LCG_Interfaces (no_auto_imports) (no_version_directory)
#             use xrootd v* LCG_Interfaces (no_version_directory) (native_version=3.3.6)
#               use LCG_Configuration v*  (no_version_directory)
#               use LCG_Settings v*  (no_version_directory)
#         use Boost * LCG_Interfaces (no_version_directory) (native_version=1.57.0_python2.7)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#           use Python v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.11)
#         use CppUnit * LCG_Interfaces (private) (no_auto_imports) (no_version_directory) (native_version=1.12.1_p1)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#       use GaudiUtils * Gaudi (no_version_directory)
#         use GaudiKernel * Gaudi (no_version_directory)
#         use ROOT * LCG_Interfaces (no_version_directory)
#         use AIDA * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3.2.1)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#         use Boost * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.57.0_python2.7)
#         use uuid * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.38p1)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#         use Reflex * LCG_Interfaces (no_auto_imports) (no_version_directory)
#         use XercesC * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3.1.1p1)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#         use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#           use GaudiKernel * Gaudi (no_version_directory)
#           use CLHEP * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.9.4.7)
#             use LCG_Configuration v*  (no_version_directory)
#             use LCG_Settings v*  (no_version_directory)
#           use AIDA * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3.2.1)
#           use Boost * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.57.0_python2.7)
#           use ROOT * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=5.34.36)
#       use ROOT * LCG_Interfaces (no_version_directory) (native_version=5.34.36)
#       use AIDA * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3.2.1)
#       use Boost * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.57.0_python2.7)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#     use GaudiAud v9r4 Gaudi (no_version_directory)
#       use GaudiKernel * Gaudi (no_version_directory)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#     use GaudiGSL v7r10 Gaudi (no_version_directory)
#       use GaudiKernel * Gaudi (no_version_directory)
#       use GaudiAlg * Gaudi (no_version_directory)
#       use GSL * LCG_Interfaces (no_version_directory) (native_version=1.10)
#         use LCG_Configuration v*  (no_version_directory)
#         use LCG_Settings v*  (no_version_directory)
#       use CLHEP * LCG_Interfaces (no_version_directory) (native_version=1.9.4.7)
#       use AIDA * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3.2.1)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#     use GaudiKernel v27r16p1 Gaudi (no_version_directory)
#     use GaudiObjDesc v11r12 Gaudi (no_version_directory)
#       use Python v* LCG_Interfaces (no_version_directory) (native_version=2.7.11)
#       use GaudiPolicy v* Gaudi (no_version_directory)
#     use GaudiPolicy v11r4 Gaudi (no_version_directory)
#     use GaudiPoolDb v5r12 Gaudi (no_version_directory)
#       use GaudiKernel * Gaudi (no_version_directory)
#       use GaudiUtils * Gaudi (no_version_directory)
#       use POOL * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=POOL_2_9_19)
#         use LCG_Configuration v*  (no_version_directory)
#         use LCG_Settings v*  (no_version_directory)
#         use CORAL v* LCG_Interfaces (no_version_directory) (native_version=CORAL_2_3_27a)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#           use Boost v* LCG_Interfaces (no_version_directory)
#         use Boost v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.57.0_python2.7)
#         use ROOT v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=5.34.36)
#         use XercesC v* LCG_Interfaces (no_auto_imports) (no_version_directory)
#       use CORAL * LCG_Interfaces (no_auto_imports) (no_version_directory)
#       use Reflex * LCG_Interfaces (no_auto_imports) (no_version_directory)
#       use RELAX * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=RELAX_1_3_0p)
#         use LCG_Configuration v*  (no_version_directory)
#         use LCG_Settings v*  (no_version_directory)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#       use ROOT * LCG_Interfaces (private) (no_version_directory) (native_version=5.34.36)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#     use GaudiPython v11r1 Gaudi (no_auto_imports) (no_version_directory)
#       use GaudiKernel * Gaudi (no_version_directory)
#       use GaudiAlg * Gaudi (no_version_directory)
#       use GaudiUtils * Gaudi (no_version_directory)
#       use AIDA * LCG_Interfaces (no_version_directory) (native_version=3.2.1)
#       use CLHEP * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.9.4.7)
#       use Python * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.11)
#       use Reflex * LCG_Interfaces (no_auto_imports) (no_version_directory)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#     use GaudiSvc v18r16p1 Gaudi (no_version_directory)
#     use GaudiUtils v3r13 Gaudi (no_version_directory)
#     use PartPropSvc v4r2 Gaudi (no_version_directory)
#       use GaudiPolicy * Gaudi (no_version_directory)
#       use GaudiKernel * Gaudi (no_version_directory)
#       use HepPDT * LCG_Interfaces (no_version_directory) (native_version=2.06.01)
#         use LCG_Configuration v*  (no_version_directory)
#         use LCG_Settings v*  (no_version_directory)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#     use RootHistCnv v10r7 Gaudi (no_version_directory)
#       use GaudiKernel * Gaudi (no_version_directory)
#       use AIDA * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3.2.1)
#       use ROOT * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=5.34.36)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#   use pytools * LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=1.6_python2.7)
#     use LCG_Configuration v*  (no_version_directory)
#     use LCG_Settings v*  (no_version_directory)
#     use Python v* LCG_Interfaces (no_version_directory) (native_version=2.7.11)
#     use mysql v* LCG_Interfaces (no_version_directory) (native_version=5.5.14)
#       use LCG_Configuration v*  (no_version_directory)
#       use LCG_Settings v*  (no_version_directory)
# use MinervaEvent v* Event (no_version_directory)
#   use Gaudi v* Gaudi (no_version_directory)
#   use GaudiPoolDb v* Gaudi (no_auto_imports) (no_version_directory)
#   use GaudiSvc v* Gaudi (no_auto_imports) (no_version_directory)
#   use MinervaKernel v* Event (no_version_directory)
#     use MinervaPolicy v* Top (no_version_directory)
#       use GaudiPolicy v* Gaudi (no_auto_imports) (no_version_directory)
#     use GaudiKernel v* Gaudi (no_version_directory)
#     use CLHEP v* LCG_Interfaces (no_version_directory)
#     use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.57.0_python2.7)
#     use ROOT v* LCG_Interfaces (no_version_directory) (native_version=5.34.36)
#     use GaudiObjDesc v* Gaudi (private) (no_auto_imports) (no_version_directory)
#     use GaudiAlg v* Gaudi (private) (no_version_directory)
#   use EventInterfaces v* Event (no_version_directory)
#     use Gaudi v* Gaudi (no_version_directory)
#   use ROOT v* LCG_Interfaces (no_version_directory) (native_version=5.34.36)
#   use GaudiAlg v* Gaudi (private) (no_auto_imports) (no_version_directory)
#   use GaudiObjDesc v* Gaudi (private) (no_auto_imports) (no_version_directory)
#   use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
# use MinervaDet v* Det (no_version_directory)
#   use MinervaKernel v* Event (no_version_directory)
#   use ODDet v* Det (no_version_directory)
#     use MinervaKernel v* Event (no_version_directory)
#     use DetDesc v* Det (no_version_directory)
#       use GaudiKernel v* Gaudi (no_version_directory)
#       use ROOT v* LCG_Interfaces (no_version_directory) (native_version=5.34.36)
#       use HistoStrings v* Kernel (no_version_directory)
#         use GaudiKernel v* Gaudi (no_version_directory)
#         use GaudiUtils v* Gaudi (no_version_directory)
#         use AIDA v* LCG_Interfaces (no_version_directory)
#         use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.57.0_python2.7)
#         use ROOT v* LCG_Interfaces (no_version_directory) (native_version=5.34.36)
#       use LHCbMath v* Kernel (no_version_directory)
#         use GaudiKernel v* Gaudi (no_version_directory)
#         use ROOT v* LCG_Interfaces (no_version_directory) (native_version=5.34.36)
#         use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.57.0_python2.7)
#         use GSL v* LCG_Interfaces (no_version_directory)
#         use GaudiPython v* Gaudi (no_auto_imports) (no_version_directory)
#     use DetDescCnv v* Det (no_version_directory)
#       use DetDesc v* Det (no_version_directory)
#       use XmlTools v* Tools (no_version_directory)
#         use GaudiKernel v* Gaudi (no_version_directory)
#         use XercesC v* LCG_Interfaces (no_version_directory) (native_version=3.1.1p1)
#         use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#       use GaudiKernel v* Gaudi (no_version_directory)
#       use XercesC v* LCG_Interfaces (no_version_directory) (native_version=3.1.1p1)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#     use GaudiAlg v* Gaudi (no_version_directory)
#     use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#   use DetDesc v* Det (no_version_directory)
#   use DetDescCnv v* Det (no_version_directory)
#   use GaudiAlg v* Gaudi (no_version_directory)
#   use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
# use Plex v* Det (no_version_directory)
#   use GaudiAlg v* Gaudi (no_version_directory)
#   use MinervaEvent v* Event (no_version_directory)
#   use MinervaDet v* Det (no_version_directory)
#   use MinervaXmlConditions v* Det (no_version_directory)
#   use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
# use Attenuation v* Cal (no_version_directory)
#   use Gaudi v* Gaudi (no_version_directory)
#   use MinervaUtils v* Tools (no_version_directory)
#     use GaudiAlg v* Gaudi (no_version_directory)
#     use MinervaEvent v* Event (no_version_directory)
#     use MinervaGenEvent v* Event (no_version_directory)
#       use HepMC v* LCG_Interfaces (no_version_directory) (native_version=2.06.08)
#         use LCG_Configuration v*  (no_version_directory)
#         use LCG_Settings v*  (no_version_directory)
#       use MinervaKernel v* Event (no_version_directory)
#       use MinervaMCEvent v* Event (no_version_directory)
#         use MinervaEventBase v* Event (no_version_directory)
#           use MinervaKernel v* Event (no_version_directory)
#           use GaudiObjDesc v* Gaudi (private) (no_auto_imports) (no_version_directory)
#         use MinervaEvent v* Event (no_version_directory)
#         use HepMC v* LCG_Interfaces (no_version_directory) (native_version=2.06.08)
#         use GaudiObjDesc v* Gaudi (private) (no_auto_imports) (no_version_directory)
#       use MinervaEventBase v* Event (no_version_directory)
#       use MinervaEvent v* Event (no_version_directory)
#       use ROOT v* LCG_Interfaces (no_version_directory) (native_version=5.34.36)
#       use GaudiObjDesc v* Gaudi (private) (no_auto_imports) (no_version_directory)
#     use MinervaDet v* Det (no_version_directory)
#     use IDDet v* Det (no_version_directory)
#       use MinervaKernel v* Event (no_version_directory)
#       use DetDesc v* Det (no_version_directory)
#       use DetDescCnv v* Det (no_version_directory)
#       use GaudiAlg v* Gaudi (no_version_directory)
#       use MinervaDet v* Det (no_version_directory)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#     use ODDet v* Det (no_version_directory)
#     use MinervaXmlConditions v* Det (no_version_directory)
#     use MinervaDDDB v* Det (no_version_directory)
#       use MinervaXmlConditions v* Det (no_version_directory)
#       use Python v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.11)
#     use MinervaDDDBIF v* Det (no_version_directory)
#       use MinervaSQLDDDB v* Det (no_version_directory)
#       use DetCond v* Det (no_auto_imports) (no_version_directory)
#         use GaudiKernel v* Gaudi (no_version_directory)
#         use GaudiAlg v* Gaudi (no_version_directory)
#         use COOL v* LCG_Interfaces (no_version_directory) (native_version=COOL_2_8_20)
#           use LCG_Configuration v*  (no_version_directory)
#           use LCG_Settings v*  (no_version_directory)
#           use CORAL v* LCG_Interfaces (no_version_directory) (native_version=CORAL_2_3_27a)
#           use Python v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=2.7.11)
#           use ROOT v* LCG_Interfaces (no_version_directory) (native_version=5.34.36)
#         use CORAL v* LCG_Interfaces (no_version_directory) (native_version=CORAL_2_3_27a)
#         use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.57.0_python2.7)
#         use DetDesc v* Det (no_version_directory)
#         use LHCbKernel v* Kernel (no_version_directory)
#           use LHCbMath v* Kernel (no_version_directory)
#           use GaudiKernel v* Gaudi (no_version_directory)
#           use Boost v* LCG_Interfaces (no_version_directory) (native_version=1.57.0_python2.7)
#           use ROOT v* LCG_Interfaces (no_version_directory) (native_version=5.34.36)
#           use GaudiObjDesc v* Gaudi (private) (no_auto_imports) (no_version_directory)
#           use GaudiAlg v* Gaudi (private) (no_auto_imports) (no_version_directory)
#         use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#       use CondDBEntityResolver v* Tools (no_auto_imports) (no_version_directory)
#         use XmlTools v* Tools (no_version_directory)
#         use DetCond v* Det (no_version_directory)
#         use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#       use sqlite v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=3070900)
#         use LCG_Configuration v*  (no_version_directory)
#         use LCG_Settings v*  (no_version_directory)
#     use Plex v* Det (no_version_directory)
#     use AIDA v* LCG_Interfaces (no_version_directory) (native_version=3.2.1)
#     use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#   use MinervaConf v* Top (no_version_directory)
#     use MinervaPolicy v* Top (no_version_directory)
#     use ROOT v* LCG_Interfaces (no_version_directory) (native_version=5.34.36)
#     use GaudiKernel v* Gaudi (no_version_directory)
#     use GaudiPoolDb v* Gaudi (no_version_directory)
#     use MinervaDDDB v* Det (no_version_directory)
#     use MinervaDDDBIF v* Det (no_version_directory)
#   use MinervaKernel v* Event (no_version_directory)
#   use MinervaEvent v* Event (no_version_directory)
#   use MinervaDet v* Det (no_version_directory)
#   use ODDet v* Det (no_version_directory)
#   use Plex v* Det (no_version_directory)
#   use RecInterfaces v* Rec (no_version_directory)
#     use MinervaEvent v* Event (no_version_directory)
#     use MinervaUtils v* Tools (no_version_directory)
#   use RecUtils v* Rec (no_version_directory)
#     use MinervaDDDBIF v* Det (no_version_directory)
#     use MinervaDDDB v* Det (no_version_directory)
#     use MinervaDet v* Det (no_version_directory)
#     use ODDet v* Det (no_version_directory)
#     use VetoDet v* Det (no_version_directory)
#       use MinervaKernel v* Event (no_version_directory)
#       use DetDesc v* Det (no_version_directory)
#       use DetDescCnv v* Det (no_version_directory)
#       use GaudiAlg v* Gaudi (no_version_directory)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#     use MinervaKernel v* Event (no_version_directory)
#     use RecInterfaces v* Rec (no_version_directory)
#     use ClusterFormation v* Rec (no_version_directory)
#       use MinervaUtils v* Tools (no_version_directory)
#       use MinervaDet v* Det (no_version_directory)
#       use ODDet v* Det (no_version_directory)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#     use GeoUtils v* Rec (no_version_directory)
#       use MinervaUtils v* Tools (no_version_directory)
#       use MinervaDet v* Det (no_version_directory)
#       use RecInterfaces v* Rec (no_version_directory)
#       use GiGaCnv v* Sim (no_version_directory)
#         use MinervaPolicy v* Top (no_version_directory)
#         use MinervaGenEvent v* Event (no_version_directory)
#         use MinervaMCEvent v* Event (no_version_directory)
#         use DetDesc v* Det (no_version_directory)
#         use GiGa v* Sim (no_version_directory)
#           use MinervaPolicy v* Top (no_version_directory)
#           use GaudiAlg v* Gaudi (no_version_directory)
#           use G4readout v* Geant4 (no_version_directory)
#             use G4run v* Geant4 (no_version_directory)
#               use G4event v* Geant4 (no_version_directory)
#                 use G4tracking v* Geant4 (no_version_directory)
#                   use G4digits_hits v* Geant4 (no_version_directory)
#                     use G4track v* Geant4 (no_version_directory)
#                       use G4particles v* Geant4 (no_version_directory)
#                         use G4materials v* Geant4 (no_version_directory)
#                           use G4global v* Geant4 (no_version_directory)
#                             use G4config v* Geant4 (no_version_directory)
#                               use GaudiPolicy v* Gaudi (no_auto_imports) (no_version_directory)
#                               use CLHEP v* LCG_Interfaces (no_version_directory) (native_version=1.9.4.7)
#                           use G4intercoms v* Geant4 (no_version_directory)
#                             use G4global v* Geant4 (no_version_directory)
#                         use G4intercoms v* Geant4 (no_version_directory)
#                       use G4geometry v* Geant4 (no_version_directory)
#                         use G4intercoms v* Geant4 (no_version_directory)
#                         use G4graphics_reps v* Geant4 (no_version_directory)
#                           use G4global v* Geant4 (no_version_directory)
#                           use G4intercoms v* Geant4 (no_version_directory)
#                         use G4materials v* Geant4 (no_version_directory)
#                   use G4processes v* Geant4 (no_version_directory)
#                     use G4digits_hits v* Geant4 (no_version_directory)
#           use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#         use ClhepTools v* Tools (no_version_directory)
#           use MinervaPolicy v* Top (no_version_directory)
#           use CLHEP v* LCG_Interfaces (no_version_directory) (native_version=1.9.4.7)
#           use GaudiKernel v* Gaudi (no_version_directory)
#         use GDML v*  (no_version_directory)
#           use MINEXTERNAL *  (no_version_directory)
#           use XercesC v* LCG_Interfaces (no_version_directory) (native_version=3.1.1p1)
#           use CLHEP v* LCG_Interfaces (no_version_directory) (native_version=1.9.4.7)
#           use G4config v* Geant4 (no_auto_imports) (no_version_directory)
#         use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#     use EnergyRecTools v* Rec (no_version_directory)
#       use MinervaUtils v* Tools (no_version_directory)
#       use MParamFiles v*  (no_version_directory)
#       use IDDet v* Det (no_version_directory)
#       use ODDet v* Det (no_version_directory)
#       use RecInterfaces v* Rec (no_version_directory)
#       use GeoUtils v* Rec (no_version_directory)
#       use ReadoutInterfaces v* Sim (no_version_directory)
#         use MinervaEvent v* Event (no_version_directory)
#         use MinervaMCEvent v* Event (no_version_directory)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#     use BadChannels v* Cal (no_version_directory)
#       use GaudiAlg v* Gaudi (no_version_directory)
#       use MinervaConf v* Top (no_version_directory)
#       use MinervaKernel v* Event (no_version_directory)
#       use MinervaEvent v* Event (no_version_directory)
#       use MinervaDet v* Det (no_version_directory)
#       use Plex v* Det (no_version_directory)
#       use MinervaUtils v* Tools (no_version_directory)
#       use NuConDB v*  (no_version_directory)
#         use psycopg2 v*  (no_version_directory)
#           use MINEXTERNAL *  (no_version_directory)
#           use Python v* LCG_Interfaces (no_version_directory) (native_version=2.7.11)
#           use postgres_client v*  (no_version_directory)
#             use MINEXTERNAL *  (no_version_directory)
#             use Python v* LCG_Interfaces (no_version_directory) (native_version=2.7.11)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#     use MinervaUtils v* Tools (no_version_directory)
#     use AIDA v* LCG_Interfaces (no_version_directory) (native_version=3.2.1)
#     use ROOT v* LCG_Interfaces (no_version_directory) (native_version=5.34.36)
#     use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#   use NuConDB v*  (no_version_directory)
#   use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
# use RawToDigit v* Cal (no_version_directory)
#   use GaudiAlg v* Gaudi (no_version_directory)
#   use MinervaConf v* Top (no_version_directory)
#   use MinervaUtils v* Tools (no_version_directory)
#   use MinervaEvent v* Event (no_version_directory)
#   use MinervaXmlConditions v* Det (no_version_directory)
#   use Plex v* Det (no_version_directory)
#   use MinervaDet v* Det (no_version_directory)
#   use ODDet v* Det (no_version_directory)
#   use Attenuation v* Cal (no_version_directory)
#   use NuConDB v*  (no_version_directory)
#   use BadChannels v* Cal (no_version_directory)
#   use GateQuality v* Cal (no_version_directory)
#     use GaudiAlg v* Gaudi (no_version_directory)
#     use MinervaEvent v* Event (no_version_directory)
#     use MinervaUtils v* Tools (no_version_directory)
#     use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#   use Temperature v* Cal (no_version_directory)
#     use Gaudi v* Gaudi (no_version_directory)
#     use MinervaEvent v* Event (no_version_directory)
#     use MinervaDet v* Det (no_version_directory)
#     use ROOT v* LCG_Interfaces (no_version_directory) (native_version=5.34.36)
#     use mysql v* LCG_Interfaces (no_version_directory) (native_version=5.5.14)
#     use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#   use MParamFiles v*  (no_version_directory)
#   use RecUtils v* Rec (no_version_directory)
#   use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
# use NumiInterface v* Tools (no_version_directory)
#   use GaudiAlg v* Gaudi (no_version_directory)
#   use MinervaUtils v* Tools (no_version_directory)
#   use MinosGeom v*  (no_version_directory)
#     use MINEXTERNAL *  (no_version_directory)
#     use ROOT v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=5.34.36)
#     use mysql v* LCG_Interfaces (no_version_directory) (native_version=5.5.14)
#     use NumiBeamDB v*  (no_version_directory)
#       use MINEXTERNAL *  (no_version_directory)
#       use ROOT v* LCG_Interfaces (no_auto_imports) (no_version_directory) (native_version=5.34.36)
#       use mysql v* LCG_Interfaces (no_version_directory) (native_version=5.5.14)
#   use NumiBeamDB v*  (no_version_directory)
#   use NuConDB v*  (no_version_directory)
#   use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
# use AnaUtils v* Ana (no_version_directory)
#   use MinervaUtils v* Tools (no_version_directory)
#   use AnaInterfaces v* Ana (no_version_directory)
#     use MinervaEvent v* Event (no_version_directory)
#   use TruthMatcher v* Ana (no_version_directory)
#     use MinervaUtils v* Tools (no_version_directory)
#     use MinervaMCEvent v* Event (no_version_directory)
#     use MinervaDet v* Det (no_version_directory)
#     use ROOT v* LCG_Interfaces (no_version_directory) (native_version=5.34.36)
#     use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#   use BadChannels v* Cal (no_version_directory)
#   use GeoUtils v* Rec (no_version_directory)
#   use RecUtils v* Rec (no_version_directory)
#   use EnergyRecTools v* Rec (no_version_directory)
#   use BlobFormation v* Rec (no_version_directory)
#     use MinervaDet v* Det (no_version_directory)
#     use IDDet v* Det (no_version_directory)
#     use ODDet v* Det (no_version_directory)
#     use MinervaEvent v* Event (no_version_directory)
#     use RecInterfaces v* Rec (no_version_directory)
#     use RecUtils v* Rec (no_version_directory)
#     use MinervaUtils v* Tools (no_version_directory)
#     use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#   use ProngMaker v* Rec (no_version_directory)
#     use ODDet v* Det (no_version_directory)
#     use VetoDet v* Det (no_version_directory)
#     use MinervaDet v* Det (no_version_directory)
#     use MinervaUtils v* Tools (no_version_directory)
#     use MinosInterface v* Tools (no_version_directory)
#       use GaudiKernel v* Gaudi (no_version_directory)
#       use GaudiAlg v* Gaudi (no_version_directory)
#       use MinervaConf v* Top (no_version_directory)
#       use MinervaKernel v* Event (no_version_directory)
#       use MinervaEvent v* Event (no_version_directory)
#       use MinervaUtils v* Tools (no_version_directory)
#       use ROOT v* LCG_Interfaces (no_version_directory) (native_version=5.34.36)
#       use AIDA v* LCG_Interfaces (no_version_directory) (native_version=3.2.1)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#     use Attenuation v* Cal (no_version_directory)
#     use RawToDigit v* Cal (no_version_directory)
#     use BlobFormation v* Rec (no_version_directory)
#     use EnergyRecTools v* Rec (no_version_directory)
#     use GeoUtils v* Rec (no_version_directory)
#     use RecUtils v* Rec (no_version_directory)
#     use VertexCreation v* Rec (no_version_directory)
#       use GaudiAlg v* Gaudi (no_version_directory)
#       use MinervaEvent v* Event (no_version_directory)
#       use MinervaDet v* Det (no_version_directory)
#       use IDDet v* Det (no_version_directory)
#       use MinervaUtils v* Tools (no_version_directory)
#       use RecInterfaces v* Rec (no_version_directory)
#       use RecUtils v* Rec (no_version_directory)
#       use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#     use AIDA v* LCG_Interfaces (no_version_directory) (native_version=3.2.1)
#     use ROOT v* LCG_Interfaces (no_version_directory) (native_version=5.34.36)
#     use GaudiPython v* Gaudi (no_version_directory)
#     use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
#   use EventRecInterfaces v* Rec (no_version_directory)
#     use MinervaEvent v* Event (no_version_directory)
#     use MinervaUtils v* Tools (no_version_directory)
#   use MinervaDet v* Det (no_version_directory)
#   use Plex v* Det (no_version_directory)
#   use AIDA v* LCG_Interfaces (no_version_directory) (native_version=3.2.1)
#   use ROOT v* LCG_Interfaces (no_version_directory) (native_version=5.34.36)
#   use GaudiSvc * Gaudi (private) (no_auto_imports) (no_version_directory)
# use GaudiSvc * Gaudi (no_auto_imports) (no_version_directory)
#
# Selection :
use CMT v1r20p20090520 (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/lcgcmake/lcg_61a_forSL7/external/cmt/v1r20p20090520/x86_64-slc7-gcc49-opt)
use MParamFiles ${MINERVA_RELEASE}  (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MDBASE/MDBASE_v22r1p1)
use MINEXTERNAL ${MINERVA_RELEASE}  (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/EXTERNAL/EXTERNAL_v22r1p1)
use MinervaSQLDDDB ${MINERVA_RELEASE} Det (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MDBASE/MDBASE_v22r1p1/)
use MinervaXmlConditions ${MINERVA_RELEASE} Det (/minerva/app/users/rvizarr/cmtuser/Minerva_v22r1p1_2x2/)
use LCG_Platforms v1  (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61)
use LCG_Configuration v1  (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61)
use LCG_Settings v1  (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61)
use sqlite v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/) (no_auto_imports)
use HepMC v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/)
use mysql v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/)
use HepPDT v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/)
use RELAX v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/) (no_auto_imports)
use GSL v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/)
use CLHEP v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/)
use XercesC v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/)
use uuid v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/) (no_auto_imports)
use AIDA v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/)
use CppUnit v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/) (no_auto_imports)
use xrootd v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/)
use GCCXML v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/) (no_auto_imports)
use libunwind v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/) (no_auto_imports)
use tcmalloc v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/) (no_auto_imports)
use Python v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/)
use postgres_client v9r1p14  (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/EXTERNAL/EXTERNAL_v22r1p1)
use psycopg2 v2r5p4  (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/EXTERNAL/EXTERNAL_v22r1p1)
use NuConDB ${MINERVA_RELEASE}  (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/EXTERNAL/EXTERNAL_v22r1p1)
use MinervaDDDB ${MINERVA_RELEASE} Det (/minerva/app/users/rvizarr/cmtuser/Minerva_v22r1p1_2x2/)
use pytools v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/) (no_auto_imports)
use Boost v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/)
use CORAL v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/) (no_auto_imports)
use ROOT v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/)
use NumiBeamDB ${MINERVA_RELEASE}  (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/EXTERNAL/EXTERNAL_v22r1p1)
use MinosGeom ${MINERVA_RELEASE}  (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/EXTERNAL/EXTERNAL_v22r1p1)
use COOL v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/) (no_auto_imports)
use POOL v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/) (no_auto_imports)
use Reflex v1 LCG_Interfaces (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61/)
use GaudiPolicy v11r4 Gaudi (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GAUDI/GAUDI_v22r4b_lcgcmake/)
use G4config v94r2p2 Geant4 (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GEANT4/GEANT4_v94r2p2b_lcgcmake/)
use GDML ${MINERVA_RELEASE}  (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/EXTERNAL/EXTERNAL_v22r1p1)
use G4global v5r1p1 Geant4 (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GEANT4/GEANT4_v94r2p2b_lcgcmake/)
use G4intercoms v4r1p1 Geant4 (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GEANT4/GEANT4_v94r2p2b_lcgcmake/)
use G4graphics_reps v4r1p1 Geant4 (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GEANT4/GEANT4_v94r2p2b_lcgcmake/)
use G4materials v5r0p1 Geant4 (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GEANT4/GEANT4_v94r2p2b_lcgcmake/)
use G4geometry v6r2p1 Geant4 (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GEANT4/GEANT4_v94r2p2b_lcgcmake/)
use G4particles v6r2p1 Geant4 (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GEANT4/GEANT4_v94r2p2b_lcgcmake/)
use G4track v5r1p1 Geant4 (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GEANT4/GEANT4_v94r2p2b_lcgcmake/)
use G4digits_hits v7r1p1 Geant4 (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GEANT4/GEANT4_v94r2p2b_lcgcmake/)
use G4processes v8r1 Geant4 (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GEANT4/GEANT4_v94r2p2b_lcgcmake/)
use G4tracking v6r1p1 Geant4 (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GEANT4/GEANT4_v94r2p2b_lcgcmake/)
use G4event v6r0p1 Geant4 (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GEANT4/GEANT4_v94r2p2b_lcgcmake/)
use G4run v5r1p1 Geant4 (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GEANT4/GEANT4_v94r2p2b_lcgcmake/)
use G4readout v4r1p1 Geant4 (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GEANT4/GEANT4_v94r2p2b_lcgcmake/)
use MinervaPolicy ${MINERVA_RELEASE} Top (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use GaudiObjDesc v11r12 Gaudi (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GAUDI/GAUDI_v22r4b_lcgcmake/)
use GaudiKernel v27r16 Gaudi (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GAUDI/GAUDI_v22r4b_lcgcmake/)
use ClhepTools ${MINERVA_RELEASE} Tools (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use GaudiSvc v18r16 Gaudi (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GAUDI/GAUDI_v22r4b_lcgcmake/)
use XmlTools v6r6 Tools (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/LHCB/LHCB_v33r0p1b_lcgcmake/)
use RootHistCnv v10r7 Gaudi (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GAUDI/GAUDI_v22r4b_lcgcmake/)
use PartPropSvc v4r2 Gaudi (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GAUDI/GAUDI_v22r4b_lcgcmake/)
use GaudiAud v9r4 Gaudi (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GAUDI/GAUDI_v22r4b_lcgcmake/)
use GaudiUtils v3r13 Gaudi (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GAUDI/GAUDI_v22r4b_lcgcmake/)
use HistoStrings v1r2 Kernel (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/LHCB/LHCB_v33r0p1b_lcgcmake/)
use GaudiPoolDb v5r12 Gaudi (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GAUDI/GAUDI_v22r4b_lcgcmake/)
use GaudiAlg v13r8 Gaudi (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GAUDI/GAUDI_v22r4b_lcgcmake/)
use GiGa ${MINERVA_RELEASE} Sim (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use MinervaKernel ${MINERVA_RELEASE} Event (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use MinervaEventBase ${MINERVA_RELEASE} Event (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use GaudiPython v11r1 Gaudi (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GAUDI/GAUDI_v22r4b_lcgcmake/)
use LHCbMath v3r26 Kernel (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/LHCB/LHCB_v33r0p1b_lcgcmake/)
use LHCbKernel v13r5 Kernel (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/LHCB/LHCB_v33r0p1b_lcgcmake/) (no_auto_imports)
use DetDesc v18r27p2 Det (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/LHCB/LHCB_v33r0p1b_lcgcmake/)
use DetCond v12r21 Det (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/LHCB/LHCB_v33r0p1b_lcgcmake/) (no_auto_imports)
use CondDBEntityResolver v5r3 Tools (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/LHCB/LHCB_v33r0p1b_lcgcmake/) (no_auto_imports)
use MinervaDDDBIF ${MINERVA_RELEASE} Det (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use MinervaConf ${MINERVA_RELEASE} Top (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use DetDescCnv v4r14 Det (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/LHCB/LHCB_v33r0p1b_lcgcmake/)
use VetoDet ${MINERVA_RELEASE} Det (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use ODDet ${MINERVA_RELEASE} Det (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use MinervaDet ${MINERVA_RELEASE} Det (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use IDDet ${MINERVA_RELEASE} Det (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use GaudiGSL v7r10 Gaudi (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GAUDI/GAUDI_v22r4b_lcgcmake/)
use GaudiSys v22r4  (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GAUDI/GAUDI_v22r4b_lcgcmake)
use Gaudi v22r4 Gaudi (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GAUDI/GAUDI_v22r4b_lcgcmake/)
use EventInterfaces ${MINERVA_RELEASE} Event (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use MinervaEvent ${MINERVA_RELEASE} Event (/minerva/app/users/rvizarr/cmtuser/Minerva_v22r1p1_2x2/)
use AnaInterfaces ${MINERVA_RELEASE} Ana (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use Temperature ${MINERVA_RELEASE} Cal (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use MinervaMCEvent ${MINERVA_RELEASE} Event (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use ReadoutInterfaces ${MINERVA_RELEASE} Sim (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use MinervaGenEvent ${MINERVA_RELEASE} Event (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use GiGaCnv ${MINERVA_RELEASE} Sim (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use Plex ${MINERVA_RELEASE} Det (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use MinervaUtils ${MINERVA_RELEASE} Tools (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use EventRecInterfaces ${MINERVA_RELEASE} Rec (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use MinosInterface ${MINERVA_RELEASE} Tools (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use TruthMatcher ${MINERVA_RELEASE} Ana (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use NumiInterface ${MINERVA_RELEASE} Tools (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use GateQuality ${MINERVA_RELEASE} Cal (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use BadChannels ${MINERVA_RELEASE} Cal (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use ClusterFormation ${MINERVA_RELEASE} Rec (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use RecInterfaces ${MINERVA_RELEASE} Rec (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use GeoUtils ${MINERVA_RELEASE} Rec (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use EnergyRecTools ${MINERVA_RELEASE} Rec (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use RecUtils ${MINERVA_RELEASE} Rec (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use VertexCreation ${MINERVA_RELEASE} Rec (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use BlobFormation ${MINERVA_RELEASE} Rec (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use Attenuation ${MINERVA_RELEASE} Cal (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use RawToDigit ${MINERVA_RELEASE} Cal (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use ProngMaker ${MINERVA_RELEASE} Rec (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
use AnaUtils ${MINERVA_RELEASE} Ana (/cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1/)
----------> tags
CMTv1 (from CMTVERSION)
CMTr20 (from CMTVERSION)
CMTp20090520 (from CMTVERSION)
Linux (from uname) package LCG_Platforms implies [Unix host-linux]
x86_64-slc7-gcc49-opt (from CMTCONFIG) package LCG_Platforms implies [target-x86_64 target-slc7 target-gcc49 target-opt]
LOCAL (from CMTSITE)
Minerva_v22r1p1_2x2_no_config (from PROJECT) excludes [Minerva_v22r1p1_2x2_config]
Minerva_v22r1p1_2x2_root (from PROJECT) excludes [Minerva_v22r1p1_2x2_no_root]
Minerva_v22r1p1_2x2_cleanup (from PROJECT) excludes [Minerva_v22r1p1_2x2_no_cleanup]
Minerva_v22r1p1_2x2_prototypes (from PROJECT) excludes [Minerva_v22r1p1_2x2_no_prototypes]
Minerva_v22r1p1_2x2_with_installarea (from PROJECT) excludes [Minerva_v22r1p1_2x2_without_installarea]
Minerva_v22r1p1_2x2_without_version_directory (from PROJECT) excludes [Minerva_v22r1p1_2x2_with_version_directory]
Minerva_v22r1p1_2x2 (from PROJECT)
MINERVA_no_config (from PROJECT) excludes [MINERVA_config]
MINERVA_root (from PROJECT) excludes [MINERVA_no_root]
MINERVA_cleanup (from PROJECT) excludes [MINERVA_no_cleanup]
MINERVA_prototypes (from PROJECT) excludes [MINERVA_no_prototypes]
MINERVA_with_installarea (from PROJECT) excludes [MINERVA_without_installarea]
MINERVA_without_version_directory (from PROJECT) excludes [MINERVA_with_version_directory]
GAUDI_no_config (from PROJECT) excludes [GAUDI_config]
GAUDI_root (from PROJECT) excludes [GAUDI_no_root]
GAUDI_cleanup (from PROJECT) excludes [GAUDI_no_cleanup]
GAUDI_prototypes (from PROJECT) excludes [GAUDI_no_prototypes]
GAUDI_with_installarea (from PROJECT) excludes [GAUDI_without_installarea]
GAUDI_without_version_directory (from PROJECT) excludes [GAUDI_with_version_directory]
LCGCMT_no_config (from PROJECT) excludes [LCGCMT_config]
LCGCMT_no_root (from PROJECT) excludes [LCGCMT_root]
LCGCMT_cleanup (from PROJECT) excludes [LCGCMT_no_cleanup]
LCGCMT_prototypes (from PROJECT) excludes [LCGCMT_no_prototypes]
LCGCMT_without_installarea (from PROJECT) excludes [LCGCMT_with_installarea]
LCGCMT_with_version_directory (from PROJECT) excludes [LCGCMT_without_version_directory]
LHCB_no_config (from PROJECT) excludes [LHCB_config]
LHCB_root (from PROJECT) excludes [LHCB_no_root]
LHCB_cleanup (from PROJECT) excludes [LHCB_no_cleanup]
LHCB_prototypes (from PROJECT) excludes [LHCB_no_prototypes]
LHCB_with_installarea (from PROJECT) excludes [LHCB_without_installarea]
LHCB_without_version_directory (from PROJECT) excludes [LHCB_with_version_directory]
GEANT4_no_config (from PROJECT) excludes [GEANT4_config]
GEANT4_root (from PROJECT) excludes [GEANT4_no_root]
GEANT4_cleanup (from PROJECT) excludes [GEANT4_no_cleanup]
GEANT4_prototypes (from PROJECT) excludes [GEANT4_no_prototypes]
GEANT4_with_installarea (from PROJECT) excludes [GEANT4_without_installarea]
GEANT4_without_version_directory (from PROJECT) excludes [GEANT4_with_version_directory]
MDBASE_no_config (from PROJECT) excludes [MDBASE_config]
MDBASE_root (from PROJECT) excludes [MDBASE_no_root]
MDBASE_cleanup (from PROJECT) excludes [MDBASE_no_cleanup]
MDBASE_prototypes (from PROJECT) excludes [MDBASE_no_prototypes]
MDBASE_without_installarea (from PROJECT) excludes [MDBASE_with_installarea]
MDBASE_without_version_directory (from PROJECT) excludes [MDBASE_with_version_directory]
EXTERNAL_no_config (from PROJECT) excludes [EXTERNAL_config]
EXTERNAL_root (from PROJECT) excludes [EXTERNAL_no_root]
EXTERNAL_cleanup (from PROJECT) excludes [EXTERNAL_no_cleanup]
EXTERNAL_prototypes (from PROJECT) excludes [EXTERNAL_no_prototypes]
EXTERNAL_without_installarea (from PROJECT) excludes [EXTERNAL_with_installarea]
EXTERNAL_without_version_directory (from PROJECT) excludes [EXTERNAL_with_version_directory]
x86_64 (from package CMT) package LCG_Platforms implies [host-x86_64]
sl79 (from package CMT)
gcc493 (from package CMT) package LCG_Platforms implies [host-gcc49]
Unix (from package CMT) package LCG_Platforms implies [host-unix] package LCG_Platforms excludes [WIN32 Win32]
target-unix (from package LCG_Settings)
target-x86_64 (from package LCG_Settings)
target-gcc49 (from package LCG_Settings) package LCG_Platforms implies [target-gcc4 target-c11]
host-x86_64 (from package LCG_Settings)
target-slc (from package LCG_Settings) package LCG_Platforms implies [target-linux]
target-gcc (from package LCG_Settings)
target-gcc4 (from package LCG_Settings) package LCG_Platforms implies [target-gcc]
host-gcc4 (from package LCG_Platforms) package LCG_Platforms implies [host-gcc]
host-gcc49 (from package LCG_Platforms) package LCG_Platforms implies [host-gcc4]
host-gcc (from package LCG_Platforms)
host-linux (from package LCG_Platforms) package LCG_Platforms implies [host-unix]
host-unix (from package LCG_Platforms)
target-opt (from package LCG_Platforms)
target-slc7 (from package LCG_Platforms) package LCG_Platforms implies [target-slc]
target-linux (from package LCG_Platforms) package LCG_Platforms implies [target-unix]
target-c11 (from package LCG_Platforms)
ROOT_GE_5_15 (from package LCG_Configuration)
ROOT_GE_5_19 (from package LCG_Configuration)
lcgcmake (from package LCG_Configuration)
NEEDS_CORAL_RELATIONAL_ACCESS (from package CORAL)
NEEDS_CORAL_BASE (from package CORAL)
POOL_HAS_SERVICES (from package POOL) package POOL implies [POOL_HAS_CORE]
POOL_HAS_CORE (from package POOL)
POOL_HAS_FILEMGT (from package POOL) package POOL implies [POOL_HAS_SERVICES]
POOL_HAS_COLLECTIONS (from package POOL) package POOL implies [POOL_HAS_CORE]
POOL_HAS_PERSISTENCY (from package POOL) package POOL implies [POOL_HAS_COLLECTIONS POOL_HAS_FILEMGT]
NEEDS_COOL_FACTORY (from package COOL)
NEEDS_PYCOOL (from package COOL)
----------> CMTPATH
# Add path /minerva/app/users/rvizarr/cmtuser/Minerva_v22r1p1_2x2 from initialization
# Add path /cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MINERVA/MINERVA_v22r1p1 from ProjectPath
# Add path /cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/LHCB/LHCB_v33r0p1b_lcgcmake from ProjectPath
# Add path /cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/EXTERNAL/EXTERNAL_v22r1p1 from ProjectPath
# Add path /cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GEANT4/GEANT4_v94r2p2b_lcgcmake from ProjectPath
# Add path /cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/minerva/MDBASE/MDBASE_v22r1p1 from ProjectPath
# Add path /cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lhcb/GAUDI/GAUDI_v22r4b_lcgcmake from ProjectPath
# Add path /cvmfs/minerva.opensciencegrid.org/minerva/software_releases/v22r1p1/lcg/external/LCGCMT/LCGCMT_61 from ProjectPath
